version: '3.1'

services:
  mongo:
    image: mongo
    command: bash /data/configdb/init.sh
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongo_data:/data/db
      - ./init.sh:/data/configdb/init.sh
      - ./keyfile:/data/configdb/keyfile

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/?replicaSet=rs0&authSource=admin
      ME_CONFIG_BASICAUTH: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  api:
    image: driveapi:latest
    restart: always
    ports:
      - ${SPRING_APP_PORT}:${SPRING_APP_PORT}
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: ${SPRING_MONGO_URI}
      SPRING_APPLICATION_NAME: ${SPRING_APP_NAME}
      SERVER_PORT: ${SPRING_APP_PORT}
      SPRING_SECURITY_PASS: ${SPRING_SECURITY_PASS}
      SPRING_SECURITY_USER: ${SPRING_SECURITY_USER}
    volumes:
      - ./uploads:/app/uploads
volumes:
  mongo_data:
  uploads:



