name: Test SSH Connection

on:
  workflow_dispatch:  # Permet de lancer le workflow manuellement depuis GitHub Actions

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Display ip server
        run: echo "Try to connect to ${{ secrets.SERVER_HOST }} as user ${{ secrets.SERVER_USER }}"

      - name: Test SSH connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH }}
          script: |
            echo "✅ Connected to server ${{ secrets.SERVER_HOST }} 🚀"
            uname -a
            whoami  
